export const LOGINNANNY_BEGIN = 'LOGINNANNY_BEGIN';
export const LOGINNANNY_SUCCESS = 'LOGINNANNY_SUCCESS';
export const LOGINNANNY_FAIL = 'LOGINNANNY_FAIL';

export const REGISTERNANNY_BEGIN = 'REGISTERNANNY_BEGIN';
export const REGISTERNANNY_SUCCESS = 'REGISTERNANNY_SUCCESS';
export const REGISTERNANNY_FAIL = 'REGISTERNANNY_FAIL';

export const CHANGEPASSWORD_BEGIN = 'CHANGEPASSWORD_BEGIN';
export const CHANGEPASSWORD_SUCCESS = 'CHANGEPASSWORD_SUCCESS';
export const CHANGEPASSWORD_FAIL = 'CHANGEPASSWORD_FAIL';

export const GET_GETDATAPARENT_BEGIN = "GET_GETDATAPARENT_BEGIN";
export const GET_GETDATAPARENT_SUCCESS = "GET_GETDATAPARENT_SUCCESS";
export const GET_GETDATAPARENT_FAIL = "GET_GETDATAPARENT_FAIL";

export const GET_GETDATACHILD_BEGIN = "GET_GETDATACHILD_BEGIN";
export const GET_GETDATACHILD_SUCCESS = "GET_GETDATACHILD_SUCCESS";
export const GET_GETDATACHILD_FAIL = "GET_GETDATACHILD_FAIL";

export const PUT_PARENT_BEGIN = "PUT_PARENT_BEGIN";
export const PUT_PARENT_SUCCESS = "PUT_PARENT_SUCCESS";
export const PUT_PARENT_FAIL = "PUT_PARENT_FAIL";

export const POST_CHILD_BEGIN = "POST_CHILD_BEGIN";
export const POST_CHILD_SUCCESS = "POST_CHILD_SUCCESS";
export const POST_CHILD_FAIL = "POST_CHILD_FAIL";

export const POST_PARENTCHILD_BEGIN = "POST_PARENTCHILD_BEGIN";
export const POST_PARENTCHILD_SUCCESS = "POST_PARENTCHILD_SUCCESS";
export const POST_PARENTCHILD_FAIL = "POST_PARENTCHILD_FAIL";

export const GET_CHILDACTIVITYPARENT_BEGIN = "GET_CHILDACTIVITYPARENT_BEGIN";
export const GET_CHILDACTIVITYPARENT_SUCCESS = "GET_CHILDACTIVITYPARENT_SUCCESS";
export const GET_CHILDACTIVITYPARENT_FAIL = "GET_CHILDACTIVITYPARENT_FAIL";

//spaci

export const GET_ACTIVE_NANNIES_BEGIN = 'GET_ACTIVE_NANNIES_BEGIN';
export const GET_ACTIVE_NANNIES_SUCCESS = 'GET_ACTIVE_NANNIES_SUCCESS';
export const GET_ACTIVE_NANNIES_FAIL = 'GET_ACTIVE_NANNIES_FAIL';

export const GET_ACTIVE_CLIENTS_BEGIN = 'GET_ACTIVE_CLIENTS_BEGIN';
export const GET_ACTIVE_CLIENTS_SUCCESS = 'GET_ACTIVE_CLIENTS_SUCCESS';
export const GET_ACTIVE_CLIENTS_FAIL = 'GET_ACTIVE_CLIENTS_FAIL';

export const GET_APPOINTMENT_BEGIN = 'GET_APPOINTMENT_BEGIN';
export const GET_APPOINTMENT_SUCCESS = 'GET_APPOINTMENT_SUCCESS';
export const GET_APPOINTMENT_FAIL = 'GET_APPOINTMENT_FAIL';

export const GET_NANNY_PROFILE_BEGIN = 'GET_NANNY_PROFILE_BEGIN';
export const GET_NANNY_PROFILE_SUCCESS = 'GET_NANNY_PROFILE_SUCCESS';
export const GET_NANNY_PROFILE_FAIL = 'GET_NANNY_PROFILE_FAIL';

export const UPDATE_NANNY_PROFILE_BEGIN = 'UPDATE_NANNY_PROFILE_BEGIN';
export const UPDATE_NANNY_PROFILE_SUCCESS = 'UPDATE_NANNY_PROFILE_SUCCESS';
export const UPDATE_NANNY_PROFILE_FAIL = 'UPDATE_NANNY_PROFILE_FAIL';

export const GET_NANNIES_BEGIN = 'GET_NANNIES_BEGIN';
export const GET_NANNIES_SUCCESS = 'GET_NANNIES_SUCCESS';
export const GET_NANNIES_FAIL = 'GET_NANNIES_FAIL';

export const GET_MAIN_CLIENTS_BEGIN = 'GET_MAIN_CLIENTS_BEGIN';
export const GET_MAIN_CLIENTS_SUCCESS = 'GET_MAIN_CLIENTS_SUCCESS';
export const GET_MAIN_CLIENTS_FAIL = 'GET_MAIN_CLIENTS_FAIL';

export const GET_CLIENTS_BEGIN = 'GET_CLIENTS_BEGIN';
export const GET_CLIENTS_SUCCESS = 'GET_CLIENTS_SUCCESS';
export const GET_CLIENTS_FAIL = 'GET_CLIENTS_FAIL';

export const GET_CLIENT_DETAIL_BEGIN = 'GET_CLIENT_DETAIL_BEGIN';
export const GET_CLIENT_DETAIL_SUCCESS = 'GET_CLIENT_DETAIL_SUCCESS';
export const GET_CLIENT_DETAIL_FAIL = 'GET_CLIENT_DETAIL_FAIL';

export const UPDATE_STATUS_APPOINTMENT_BEGIN = 'UPDATE_STATUS_APPOINTMENT_BEGIN';
export const UPDATE_STATUS_APPOINTMENT_SUCCESS = 'UPDATE_STATUS_APPOINTMENT_SUCCESS';
export const UPDATE_STATUS_APPOINTMENT_FAIL = 'UPDATE_STATUS_APPOINTMENT_FAIL';

export const GET_CHILD_ACTIVITY_BEGIN = 'GET_CHILD_ACTIVITY_BEGIN';
export const GET_CHILD_ACTIVITY_SUCCESS = 'GET_CHILD_ACTIVITY_SUCCESS';
export const GET_CHILD_ACTIVITY_FAIL = 'GET_CHILD_ACTIVITY_FAIL';

export const GET_CHILD_ACTIVITIES_BEGIN = 'GET_CHILD_ACTIVITIES_BEGIN';
export const GET_CHILD_ACTIVITIES_SUCCESS = 'GET_CHILD_ACTIVITIES_SUCCESS';
export const GET_CHILD_ACTIVITIES_FAIL = 'GET_CHILD_ACTIVITIES_FAIL';

export const POST_CHILD_ACTIVITIES_BEGIN = 'POST_CHILD_ACTIVITIES_BEGIN';
export const POST_CHILD_ACTIVITIES_SUCCESS = 'POST_CHILD_ACTIVITIES_SUCCESS';
export const POST_CHILD_ACTIVITIES_FAIL = 'POST_CHILD_ACTIVITIES_FAIL';

export const UPDATE_CHILD_ACTIVITIES_BEGIN = 'UPDATE_CHILD_ACTIVITIES_BEGIN';
export const UPDATE_CHILD_ACTIVITIES_SUCCESS = 'UPDATE_CHILD_ACTIVITIES_SUCCESS';
export const UPDATE_CHILD_ACTIVITIES_FAIL = 'UPDATE_CHILD_ACTIVITIES_FAIL';
