export const LOGINNANNY_BEGIN = 'LOGINNANNY_BEGIN';
export const LOGINNANNY_SUCCESS = 'LOGINNANNY_SUCCESS';
export const LOGINNANNY_FAIL = 'LOGINNANNY_FAIL';
export const REGISTERNANNY_BEGIN = 'REGISTERNANNY_BEGIN';
export const REGISTERNANNY_SUCCESS = 'REGISTERNANNY_SUCCESS';
export const REGISTERNANNY_FAIL = 'REGISTERNANNY_FAIL';

export const GETNANNYLIST_BEGIN = 'GETNANNYLIST_BEGIN';
export const GETNANNYLIST_SUCCES = 'GETNANNYLIST_SUCCES';
export const GETNANNYLIST_FAIL = 'GETNANNYLIST_FAIL';
