export const LOGINNANNY_BEGIN = 'LOGINNANNY_BEGIN';
export const LOGINNANNY_SUCCESS = 'LOGINNANNY_SUCCESS';
export const LOGINNANNY_FAIL = 'LOGINNANNY_FAIL';

export const REGISTERNANNY_BEGIN = 'REGISTERNANNY_BEGIN';
export const REGISTERNANNY_SUCCESS = 'REGISTERNANNY_SUCCESS';
export const REGISTERNANNY_FAIL = 'REGISTERNANNY_FAIL';

export const CHANGEPASSWORD_BEGIN = 'CHANGEPASSWORD_BEGIN';
export const CHANGEPASSWORD_SUCCESS = 'CHANGEPASSWORD_SUCCESS';
export const CHANGEPASSWORD_FAIL = 'CHANGEPASSWORD_FAIL';

export const GET_ACTIVE_NANNIES_BEGIN = 'GET_ACTIVE_NANNIES_BEGIN';
export const GET_ACTIVE_NANNIES_SUCCESS = 'GET_ACTIVE_NANNIES_SUCCESS';
export const GET_ACTIVE_NANNIES_FAIL = 'GET_ACTIVE_NANNIES_FAIL';

export const GET_ACTIVE_CLIENTS_BEGIN = 'GET_ACTIVE_CLIENTS_BEGIN';
export const GET_ACTIVE_CLIENTS_SUCCESS = 'GET_ACTIVE_CLIENTS_SUCCESS';
export const GET_ACTIVE_CLIENTS_FAIL = 'GET_ACTIVE_CLIENTS_FAIL';

export const GET_APPOINTMENT_BEGIN = 'GET_APPOINTMENT_BEGIN';
export const GET_APPOINTMENT_SUCCESS = 'GET_APPOINTMENT_SUCCESS';
export const GET_APPOINTMENT_FAIL = 'GET_APPOINTMENT_FAIL';

export const GET_NANNIES_BEGIN = 'GET_NANNIES_BEGIN';
export const GET_NANNIES_SUCCESS = 'GET_NANNIES_SUCCESS';
export const GET_NANNIES_FAIL = 'GET_NANNIES_FAIL';

export const GET_MAIN_CLIENTS_BEGIN = 'GET_MAIN_CLIENTS_BEGIN';
export const GET_MAIN_CLIENTS_SUCCESS = 'GET_MAIN_CLIENTS_SUCCESS';
export const GET_MAIN_CLIENTS_FAIL = 'GET_MAIN_CLIENTS_FAIL';

export const GET_CLIENTS_BEGIN = 'GET_CLIENTS_BEGIN';
export const GET_CLIENTS_SUCCESS = 'GET_CLIENTS_SUCCESS';
export const GET_CLIENTS_FAIL = 'GET_CLIENTS_FAIL';

export const GET_CLIENT_DETAIL_BEGIN = 'GET_CLIENT_DETAIL_BEGIN';
export const GET_CLIENT_DETAIL_SUCCESS = 'GET_CLIENT_DETAIL_SUCCESS';
export const GET_CLIENT_DETAIL_FAIL = 'GET_CLIENT_DETAIL_FAIL';

export const UPDATE_STATUS_APPOINTMENT_BEGIN = 'UPDATE_STATUS_APPOINTMENT_BEGIN';
export const UPDATE_STATUS_APPOINTMENT_SUCCESS = 'UPDATE_STATUS_APPOINTMENT_SUCCESS';
export const UPDATE_STATUS_APPOINTMENT_FAIL = 'UPDATE_STATUS_APPOINTMENT_FAIL';

export const GET_CHILD_ACTIVITY_BEGIN = 'GET_CHILD_ACTIVITY_BEGIN';
export const GET_CHILD_ACTIVITY_SUCCESS = 'GET_CHILD_ACTIVITY_SUCCESS';
export const GET_CHILD_ACTIVITY_FAIL = 'GET_CHILD_ACTIVITY_FAIL';
