const datas = [
  {
    id: 1,
    nanny: 'Sakura',
    time: '3/11/2021 07:00 PM',
    childName: 'Yugi Muto',
    activity: 'Play Bubble',
  },
  {
    id: 2,
    nanny: 'Sakura',
    time: '3/11/2021 07:00 PM',
    childName: 'Nobitakun',
    activity: 'Playing PS',
  },
  {
    id: 3,
    nanny: 'Tifa',
    time: '3/11/2021 07:00 PM',
    childName: 'Nobitakun Desu Ne',
    activity: 'Watch Boruto',
  },
  {
    id: 4,
    nanny: 'Sakura',
    time: '3/11/2021 07:00 PM',
    childName: 'Yugi Muto',
    activity: 'Eating',
  },
  {
    id: 5,
    nanny: 'Sakura',
    time: '3/11/2021 07:00 PM',
    childName: 'Aerith',
    activity: 'Sleeping',
  },
  {
    id: 6,
    nanny: 'Sakura',
    time: '3/11/2021 07:00 PM',
    childName: 'Yugi Muto',
    activity: 'Play Dart',
  },
  {
    id: 7,
    nanny: 'Sakura',
    time: '3/11/2021 07:00 PM',
    childName: 'Nobitakun',
    activity: 'Playing PS',
  },
  {
    id: 8,
    nanny: 'Tifa',
    time: '3/11/2021 07:00 PM',
    childName: 'Nobitakun Desu Ne',
    activity: 'Watch Boruto',
  },
  {
    id: 9,
    nanny: 'Aerith',
    time: '3/11/2021 07:00 PM',
    childName: 'Doraemon to Nani',
    activity: 'Eating',
  },
  {
    id: 10,
    nanny: 'Sakura',
    time: '3/11/2021 07:00 PM',
    childName: 'Sugoi Desu',
    activity: 'Sleeping',
  },
];
export default datas;
